version: "3"
services:
  lb:
    build: ./
    image: docker-lb
    ports:
      - "8080:8080"
    command: ["/bin/lb", "--verbose",  "8080:service1:8081"]

  service1:
    image: alpine
    command: ["/bin/sh", "-c", "while true; do echo 'HTTP/1.1 200 OK\n\nHello, world from '$$HOSTNAME'!' | nc -l -p 8081; done"]
