# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerLb < Formula
  desc "Lightweight TCP/HTTP/HTTPS load balancer for Docker Compose environments"
  homepage "https://github.com/jdavanne/docker-lb"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.11/docker-lb_0.0.11_darwin_amd64.tar.gz"
      sha256 "61b624ee82ffc1364aadd3e21630faff04d2a6414be8168f950b9ed5ddf34701"

      define_method(:install) do
        bin.install "docker-lb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.11/docker-lb_0.0.11_darwin_arm64.tar.gz"
      sha256 "d3152670ef50c641a1fe4881f861a183b907efb7ef7ff0a74946c919308f89aa"

      define_method(:install) do
        bin.install "docker-lb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.11/docker-lb_0.0.11_linux_amd64.tar.gz"
      sha256 "851332e10dfd1ec57693dc93e72e3571cfae3e1355a525ab03c3066d48e6cd0a"
      define_method(:install) do
        bin.install "docker-lb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.11/docker-lb_0.0.11_linux_arm64.tar.gz"
      sha256 "05d95d85b93c085a27440ccc1480d58c0414cf15a7bdbb841ce4017fb96caafb"
      define_method(:install) do
        bin.install "docker-lb"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/docker-lb --version 2>&1", 1)
  end
end
