# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerLb < Formula
  desc "Lightweight TCP/HTTP/HTTPS load balancer for Docker Compose environments"
  homepage "https://github.com/jdavanne/docker-lb"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.9/docker-lb_0.0.9_darwin_amd64.tar.gz"
      sha256 "e494c0ee11b4a8826ffebafb9969eff12ffe168b4cac2b678f54b941efaf1ed1"

      define_method(:install) do
        bin.install "docker-lb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.9/docker-lb_0.0.9_darwin_arm64.tar.gz"
      sha256 "13c2b3b06dfdb2d2c01155d0d7ff4fdc45a901ebd45ba5948c190a38451f5e88"

      define_method(:install) do
        bin.install "docker-lb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.9/docker-lb_0.0.9_linux_amd64.tar.gz"
      sha256 "0b90d3f2dcb3c9dd3bbf6ef6b9aead035d5acc1d988215c27cbf728d8786b776"
      define_method(:install) do
        bin.install "docker-lb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdavanne/docker-lb/releases/download/v0.0.9/docker-lb_0.0.9_linux_arm64.tar.gz"
      sha256 "bb68b80905d93ee25244e49d70f424fa9e13c8d6d4273a314e2832365c58ee46"
      define_method(:install) do
        bin.install "docker-lb"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/docker-lb --version 2>&1", 1)
  end
end
